# Образ
FROM python:3.9

# Установка зависимостей
COPY /files/requirements.txt /files/requirements.txt
RUN pip install -r /files/requirements.txt
# Команды для установки MSSQL драйверов для возможности обращаться в БД Аналитик из контейнера
RUN apt-get update
RUN apt -y install unixodbc-dev

RUN apt-get update && apt-get install -y gnupg2
RUN apt-get install -y curl apt-transport-https
RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
RUN curl https://packages.microsoft.com/config/debian/11/prod.list > /etc/apt/sources.list.d/mssql-release.list
RUN apt-get update
RUN ACCEPT_EULA=Y apt-get install -y msodbcsql18 unixodbc-dev

# Утсановка часового пояса внутри контейнера
RUN apt install tzdata -y
ENV TZ="Europe/Moscow"

# Рабочая директория
WORKDIR /grimer_auto

COPY ./ ./